title: "Swift Encyclopedia"
description: "Complete guide about swift birds care, feeding, and rehabilitation"
url: "https://loodus-wiki.github.io"
baseurl: "/apus-apus"

# Указываем, что сайт публикуется из /docs
#source: "."

# Плагины Jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-github-metadata
  - jekyll-optional-front-matter 
  - jekyll-relative-links       

include:
  - "ru/*.md"
  - "en/*.md" 
  - "est/*.md"

# Языки
languages:
  - code: ru
    name: Русский
    url: /apus-apus/ru/
  - code: en
    name: English
    url: /apus-apus/en/
  - code: est
    name: Eesti
    url: /apus-apus/est/

# Исключения из сборки
exclude:
  - README.md
  - LICENSE
