title: "Apus apus"
description: "Летопись стрижей"

url: "https://loodus-wiki.github.io"
baseurl: "/apus-apus"  

# Просто переменная для навигации по языкам (можно использовать в шаблоне)
languages:
  - code: ru
    name: Русский
    url: /apus-apus/ru/
  - code: en
    name: English
    url: /apus-apus/en/
  - code: est
    name: Eesti
    url: /apus-apus/est/

# Подключение плагинов, поддерживаемых GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

theme: minima
repository: loodus-wiki/apus-apus
markdown: kramdown
