title: "Apus apus"
description: "Летопись стрижей"
url: "https://loodus-wiki.github.io"
baseurl: "/apus-apus"

# Включить обработку markdown файлов
include:
  - "*.md"
  - "*/*.md"
  - "**/*.md"

# Настройки по умолчанию
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Языки
languages:
  - code: ru
    name: Русский
    url: /apus-apus/ru/
  - code: en
    name: English
    url: /apus-apus/en/
  - code: est
    name: Eesti
    url: /apus-apus/est/

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-relative-links

theme: minima
repository: loodus-wiki/apus-apus
markdown: kramdown
